### ISSUE TITLE
Unable to install Laravel-bi

### ISSUE THREAD

**Issue by tariqbilal** [laravel-bi/laravel-bi#12]
I am trying to install this Bi tool but getting following errors

Command:

composer require laravel-bi/laravel-bi

Error:

[InvalidArgumentException]                                                                                                                                                                                            
  Could not find a matching version of package laravel-bi/laravel-bi. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (dev).

**Comment by alberto-bottarini** [comment]
Hi @tariqbilal, thanks for your feedback.
I'm sorry but laravel-bi is not yet ready. It's in a development stage.

I will notify you when it will be ready to use. 

Thanks for your interest in this project :)

**Comment by VSinghhh** [comment]
Hi Alberto, any idea roughly when it is expected to be ready for others to test/play around with/use?

**Comment by alberto-bottarini** [comment]
I'm working hard to have a working version. I'll back to you in one week.

**Comment by alberto-bottarini** [comment]
Hi @tariqbilal and @VSinghhh 

Yesterday evening I updated code and documentation. Now you can find code on packagist so `composer require` starts to work :)

Please let me know about your feedback

**Comment by tariqbilal** [comment]
@alberto-bottarini thanks, I'll see how it works and get back to you.

**Comment by tariqbilal** [comment]
@alberto-bottarini it works but I am still unable to display the basic dashboard. Please update the guide if I want to create a simple dashboard with routes eg. web.php.

**Comment by alberto-bottarini** [comment]
No routes are needed. You just need to browse to /bi. This path is configurable publishing vendor file and changing config/bi.php.

You are right, documentation need some explaination. 

Thanks a lot for your feedback!

**Comment by tariqbilal** [comment]
I'll try it and get back to you again.

**Comment by alberto-bottarini** [comment]
Hey @tariqbilal . 
I hope this kind of silence brings me some great news, so that it's working and you are playing with laravel-bi :)

**Comment by tariqbilal** [comment]
Hi alberto,

Sorry, but laravel bi is not ready for the kpis we want to implement so we
are looking into other options. But we are excited to see this project
coming together

**Comment by alberto-bottarini** [comment]
You are right, is not ready to be used.
Just as a feedback, what are your requirements that laravel-bi does not meet?

Thanks a lot
